(global-set-key (kbd "M-[ B") (kbd "<down>"))
(global-set-key (kbd "M-[ C") (kbd "<right>"))
(global-set-key (kbd "M-[ D") (kbd "<left>"))
(global-set-key (kbd "M-[ a") (kbd "S-<up>"))
(global-set-key (kbd "M-[ b") (kbd "S-<down>"))
(global-set-key (kbd "M-[ c") (kbd "S-<right>"))
(global-set-key (kbd "M-[ d") (kbd "S-<left>"))
(global-set-key (kbd "M-O a") (kbd "C-<up>"))
(global-set-key (kbd "M-O b") (kbd "C-<down>"))
(global-set-key (kbd "M-O c") (kbd "C-<right>"))
(global-set-key (kbd "M-O d") (kbd "C-<left>"))
(global-set-key (kbd "ESC M-[ A") (kbd "M-<up>"))
(global-set-key (kbd "ESC M-[ B") (kbd "M-<down>"))
(global-set-key (kbd "ESC M-[ C") (kbd "M-<right>"))
(global-set-key (kbd "ESC M-[ D") (kbd "M-<left>"))

(global-set-key (kbd "<down>") 'next-line)

(global-set-key (kbd "C-x v") 'ido-switch-buffer)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-x i") 'ibuffer)
(global-set-key (kbd "C-x g") 'rgrep)
(global-set-key (kbd "C-x d") 'my-get-db)

(global-set-key (kbd "C-c g") 'goto-line)
(global-set-key (kbd "C-c r") 'query-replace)
(global-set-key (kbd "C-c a") 'align-regexp)
(global-set-key (kbd "C-c t") 'delete-trailing-whitespace)
(global-set-key (kbd "C-c w") 'backward-kill-word)
(global-set-key (kbd "C-c s") 'shrink-window)
(global-set-key (kbd "C-c e") 'enlarge-window)
(global-set-key (kbd "C-c C-u") 'uncomment-region)
(global-set-key (kbd "C-c b") 'bury-buffer)
(global-set-key (kbd "C-c c") 'comment-or-uncomment-region)
(global-set-key (kbd "C-c C-c") 'comment-or-uncomment-region)
(global-set-key (kbd "C-c i") 'delete-enclosed-text)
(global-set-key (kbd "C-c f") 'show-file-name)

(global-set-key (kbd "M-n") 'next-line)
(global-set-key (kbd "M-p") 'previous-line)
(global-set-key (kbd "M-k") 'copy-line)

(global-set-key (read-kbd-macro "<M-DEL>") 'backward-delete-word)

(global-set-key (kbd "S-<down>")     'scroll-one-line-up)
(global-set-key (kbd "S-<add>")      'scroll-one-line-up)
(global-set-key (kbd "S-<up>")       'scroll-one-line-down)
(global-set-key (kbd "S-<subtract>") 'scroll-one-line-down)

(define-key global-map "\C-cv" 'vc-prefix-map)
(global-set-key (kbd "C-c v v") 'vc-next-action)
(global-set-key (kbd "C-x m") 'magit-status)

;; Prompt before exiting Emacs.
(global-unset-key "\C-x\C-c")
(global-set-key "\C-x\C-c"
                (lambda ()
                  "Ask for confirmation before exiting emacs"
                  (interactive)
                  (if (yes-or-no-p "Are you sure you want to exit? ")
                      (save-buffers-kill-terminal))))
